### ISSUE TITLE
ModuleNotFoundError: No module named 'widgets'

### ISSUE THREAD

**Issue by KaboomPhysicist** [jesseengel/PyView#1]
Import pyview rises the error "ModuleNotFoundError: No module named 'widgets'. I have installed wxpython and pyview from pip. What is that module or what is missing?

**Comment by jesseengel** [comment]
Hi, sorry that project is really old and I can't support it anymore. Hopefully it's a helpful reference for building your own. I did just give it one final update that may fix the import issue.

Best of luck!
Jesse
